# Number of generated items
amounts:
  container_images: 50
  container_image_tags: 13
  container_groups: 50
  containers: 150
  container_group_tags: 5
  container_projects: 10
  container_project_tags: 7
  container_nodes: 50
  container_node_tags: 10
  container_templates: 50
  container_template_tags: 10
  service_instances: 10
  service_offerings: 10
  service_offering_tags: 50
  service_offering_icons: 5
  service_plans: 50
  source_regions: 5 # amazon IC
