# Number of generated items
amounts:
  cluster_service_classes: 10000
  cluster_service_plans: 50000
  namespaces: 200
  nodes: 50000
  pods: 100000
  service_instances: 10000
  templates: 5000
# Order of generating InventoryCollections:
# - :normal - top level first, dependent later
# - :reversed - dependent first
send_order: :normal
# Strategy for generating Unique IDs
# - :human_readable_uids - sequential, human readable format
# - :sequence_uuids      - sequential in UUID format
uuid_strategy: :human_readable_uids
