# Number of generated items
amounts:
  cluster_service_classes: 10000
  cluster_service_plans: 50000
  namespaces: 1000
  nodes: 50000
  pods: 100000
  service_instances: 10000
  templates: 5000

default_limit: 1000 # Number of entities to send at once to ingress api
poll_time: 5   # sleep time of main thread

full_refresh:
  # Total round of generating
  repeats_count: 1
  # Order of generating InventoryCollections:
  # - :normal - top level first, dependent later
  # - :reversed - dependent first
  send_order: :normal

# Refresh mode:
# - :full_refresh - one-time full refresh, applied settings *full_refresh*
# - :events - generated events, applied settings *targeted_refresh*
# - :standard - first full_refresh then generating events (like standard provider)
refresh_mode: :full_refresh

resource_version:
  default_value: 1
  # Strategy of creating resource version value
  # - default_value - constant
  # - timestamp - current timestamp
  # - ratio - ratio default_value/timestamp
  strategy: :default_value
  # How many percents of entities have default_value
  ratio_default_values:
    cluster_service_classes: 100
    cluster_service_plans: 100
    namespaces: 100
    nodes: 100
    pods: 100
    service_instances: 100
    templates: 100

notices:
  check_interval: 1 #second
  # Units for amount_per_hour
  # - :fixed_number
  # - :percents
  entities_per_hour_unit: :fixed_number
  entities_per_hour:
    added: 10
    modified: 10
    deleted: 10

# Strategy for generating Unique IDs
# - :human_readable - sequential, human readable format
# - :uuids          - sequential in UUID format
uuid_strategy: :human_readable
