# Number of generated items
amounts:
  cluster_service_classes: 10000
  cluster_service_plans: 50000
  namespaces: 200
  nodes: 50000
  pods: 100000
  service_instances: 10000
  templates: 5000

batch:
  size: 1000 # Number of entities to send to ingress api
  sleep: 0   # waiting time between two batches TODO not implemented

full_refresh:
  # Total round of generating
  repeats_count: 1
  # Order of generating InventoryCollections:
  # - :normal - top level first, dependent later
  # - :reversed - dependent first
  send_order: :normal

# Refresh mode:
# - :full - sequential full refresh, applied settings *full_refresh*
# - :targeted - generated events, applied settings *targeted_refresh*
refresh_mode: :full

resource_version:
  default_value: 1
  # Strategy of creating resource version value
  # - default_value - constant
  # - timestamp - current timestamp
  # - ratio - ratio default_value/timestamp
  strategy: :default_value
  # How many percents of entities have default_value
  ratio_default_values:
    cluster_service_classes: 100
    cluster_service_plans: 100
    namespaces: 100
    nodes: 100
    pods: 100
    service_instances: 100
    templates: 100

targeted_refresh: # TODO not implemented
  # Initial amounts of entities
  # - defaults - amount specified in "amounts" sections
  # - zero - no data
  initial_amount: :defaults
  amount_per_hour:
    created: 10
    updated: 10
    deleted: 10

# Strategy for generating Unique IDs
# - :human_readable - sequential, human readable format
# - :uuids          - sequential in UUID format
uuid_strategy: :human_readable
