# Number of generated items
amounts:
  container_images: 5
  container_groups: 10
  container_nodes: 5
  container_projects: 2
  container_templates: 5
  flavors: 5
  service_instances: 10
  service_offerings: 2
  service_offering_icons: 2
  service_plans: 5
  source_regions: 5
  volumes: 10              # belongs_to [:volume_type, :source_region]
  volume_types: 5
  vms: 10                  # belongs_to [:flavor]
