apiVersion: v1
kind: Template
labels:
  template: topological-inventory-secrets
metadata:
  name: topological-inventory-secrets
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: topological-inventory-database-secrets
    labels:
      app: topological-inventory
  stringData:
    hostname: topological-inventory-postgresql
    password: "${DATABASE_PASSWORD}"
    username: root
- apiVersion: v1
  kind: Secret
  metadata:
    name: topological-inventory-api-secrets
    labels:
      app: topological-inventory
  stringData:
    encryption-key: "${ENCRYPTION_KEY}"
    secret-key: "${SECRET_KEY}"
parameters:
- name: DATABASE_PASSWORD
  displayName: PostgreSQL Password
  required: true
  description: Password for the PostgreSQL user.
  from: "[a-zA-Z0-9]{20}"
  generate: expression
- name: ENCRYPTION_KEY
  displayName: Encryption Key
  required: true
  description: Encryption Key for Passwords
  from: "[a-zA-Z0-9]{43}"
  generate: expression
- name: SECRET_KEY
  displayName: Secret Key
  required: true
  description: Rails SECRET_KEY_BASE
  from: "[a-f0-9]{128}"
  generate: expression
